### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by villivateur** [NUAA-Open-Source/NUAA-iCal-Python#8]
运行环境：Windows 10 1803
NUAAiCal版本：0.5.4
python版本：3.6.5
网络环境：南京航空航天大学教学办公区

错误复现方式：
`pip3 install NUAAiCal`
`nuaaical`
测试学年：
2017-2018
2018-2019
测试学期：1&2
测试学号：若干

报错内容：
Traceback (most recent call last):
  File "c:\users\villivateur\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\villivateur\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\villivateur\AppData\Local\Programs\Python\Python36-32\Scripts\nuaaical.exe\__main__.py", line 9, in <module>
  File "c:\users\villivateur\appdata\local\programs\python\python36-32\lib\site-packages\NUAAiCal\main.py", line 95, in main
    semester_start_date = get_semester_start_date(years, xq, client)
  File "c:\users\villivateur\appdata\local\programs\python\python36-32\lib\site-packages\NUAAiCal\FindFirstDayofSemester.py", line 28, in get_semester_start_date
    with client.options(raw_response=True):
AttributeError: 'Client' object has no attribute 'options'

错误截图：
![image](https://user-images.githubusercontent.com/30222160/49357027-d29b6b00-f708-11e8-8c1e-4695970bfc3b.png)

**Comment by Triple-Z** [comment]
最新版本是 `0.5.5` ，请知悉。
